### ISSUE TITLE
OTRAG

### ISSUE THREAD

**Issue by OTRAG1** [asptu/LuaESM#1]
I started my first serious work as a 17-year old student, founding the Arbeitsgemeinschaft fuer Raketentechnik und Raumfahrt an der Universitaet Stuttgart (Working Group for Rocket Technology and Space Travel at the University of Stuttgart) in 1955. This was the first student group at a German University to be active in rocket propulsion and space flight research - at a time before the first satellites were launched and the feasibility of stable satellite orbits was still disputed in academic circles. Eugen Saenger was the mentor of the group and arranged research grants from the Baden-Wuertemberg Economic Ministry. I received the degree of Diplom-Ingenieur (equivalent to a Master of Science) in Aeronautics and Astronautics from the University of Stuttgart.

Working at the request of the Baden-Wuerttemberg government, I selected the site of the Lampoldshausen Rocket Test Centre. Together with Wolfgang Pilz, I laid out the design for the facility. In the 21st Century it remained the largest such institute in Europe.

My first major development was a bipropellant satellite attitude control systems (later sold to North American Rocketdyne and the US Air Force Rocket Propulsion Laboratory, Edwards AF Base). I also collaborated with the Rocket Engine Division of the NASA Marshall Space Flight Center in connection with the Saturn-IB clustered engine concept. I developed the first ablative combustion chamber for the H-1 engine, later tested in firings at Huntsville. This was a first step towards my concept of parallel clustering of low-cost ablative engines. Further work on the idea was supported by von Braun and jointly financed by NASA and the German Ministry of Scientific Research. I then founded Technologieforschung GmbH (TF) as a commercial spin-off to handle these and other contracts.

I invented, developed, and tested the TIROC rocket engine (Tangential Injection and Rotational Combustion). It was the world's smallest thruster burning Monomethylhydrazine and Nitrogen tetroxide. It delivered 1 newton thrust (0.2 lbf) with a minimum burning time of 1 milliseconds and a demonstrated maximum burning time of 1 million seconds (11 days). The valves had response times of under 1 millisecond and were capable of more than 1 million cycles at a 6 sigma confidence level. I also developed one of the first capillary action gas-liquid separation systems. This guaranteed positive liquid flow from propellant tanks to the rocket engines in zero-gravity. Future applications were high performance satellite and space vehicle attitude control systems.

**Comment by asptu** [comment]
combust
